#This file is created to practise the variables in Ansible
- name: This is the variable file
  hosts: localhost
  vars:
  NAME: Vasudevan Pasupuleti
  OCCUPATION: System Engineer
  tasks:
  - name: Print variables
    ansible.buildin.debug:
      msg: "Hello my name is {{NAME}} and occupation is {{OCCUPATION}}"