- name: variables at task level
  hosts: localhost
  # these variables of parent or play level
  vars:
  - money: "10000 RS"
    land: "2 hectars"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add and override
    vars:
    - money: "200000 RS"
      houses: "1 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"