- name: This is the variables from files
  hosts: localhost
  vars_files:
  - Variable.yaml
  tasks:
  - name: This is reading variables from files
    ansible.builtin.debug:
      msg: "My name is {{NAME}}, occupation is {{OCCUPATION}}"